'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

interface Stats {
  totalEvents: number;
  periodCounts: Record<string, number>;
  canGenerate: boolean;
}

interface Metadata {
  userName: string;
  totalEvents: number;
  periodsIncluded: string[];
  generatedAt: string;
  style: string;
}

const STYLES = [
  { id: 'narrative', label: 'Narrative', desc: 'Warm, engaging memoir style' },
  { id: 'poetic', label: 'Poetic', desc: 'Lyrical with metaphors' },
  { id: 'journalistic', label: 'Journalistic', desc: 'Clear, factual style' },
];

export default function LifeScriptPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [stats, setStats] = useState<Stats | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [lifeScript, setLifeScript] = useState<string | null>(null);
  const [metadata, setMetadata] = useState<Metadata | null>(null);
  const [selectedStyle, setSelectedStyle] = useState('narrative');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (status === 'loading') return;
    if (!session) { router.push('/login'); return; }
    fetchStats();
  }, [session, status, router]);

  async function fetchStats() {
    try {
      const response = await fetch('/api/life-script');
      setStats(await response.json());
    } catch (err) {
      console.error('Failed to fetch stats:', err);
    } finally {
      setLoading(false);
    }
  }

  async function generateLifeScript() {
    setGenerating(true);
    setError(null);
    try {
      const response = await fetch('/api/life-script', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ style: selectedStyle }),
      });
      const data = await response.json();
      if (!response.ok) { setError(data.error || 'Failed'); return; }
      setLifeScript(data.lifeScript);
      setMetadata(data.metadata);
    } catch (err) {
      console.error('Error:', err);
      setError('Failed to generate. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  function downloadPDF() {
    if (!lifeScript || !metadata) return;

    // Create printable HTML
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${metadata.userName}'s Life Story</title>
        <style>
          body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; padding: 20px; line-height: 1.8; color: #333; }
          h1 { text-align: center; font-size: 28px; margin-bottom: 10px; }
          .meta { text-align: center; color: #666; font-size: 14px; margin-bottom: 40px; border-bottom: 1px solid #ddd; padding-bottom: 20px; }
          h2 { font-size: 20px; margin-top: 30px; color: #444; }
          p { margin-bottom: 16px; text-align: justify; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; }
        </style>
      </head>
      <body>
        <h1>The Life Story of ${metadata.userName}</h1>
        <div class="meta">
          Generated on ${new Date(metadata.generatedAt).toLocaleDateString()}<br/>
          Based on ${metadata.totalEvents} documented life events
        </div>
        ${lifeScript.split('\n').map(p => {
          if (p.startsWith('# ')) return `<h1>${p.replace('# ', '')}</h1>`;
          if (p.startsWith('## ')) return `<h2>${p.replace('## ', '')}</h2>`;
          if (p.trim()) return `<p>${p}</p>`;
          return '';
        }).join('')}
        <div class="footer">Generated by LifeStory</div>
      </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    }
  }

  function downloadText() {
    if (!lifeScript || !metadata) return;
    const content = `THE LIFE STORY OF ${metadata.userName.toUpperCase()}\n\nGenerated: ${new Date(metadata.generatedAt).toLocaleDateString()}\nBased on ${metadata.totalEvents} life events\n\n${'='.repeat(50)}\n\n${lifeScript}\n\n${'='.repeat(50)}\nGenerated by LifeStory`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${metadata.userName.replace(/\s+/g, '_')}_Life_Story.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function copyToClipboard() {
    if (lifeScript) {
      navigator.clipboard.writeText(lifeScript);
      alert('Copied to clipboard!');
    }
  }

  if (status === 'loading' || loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-slate-600">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <Link href="/dashboard" className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
            </Link>
            <h1 className="text-lg font-semibold text-slate-900">Life Script</h1>
          </div>
          {lifeScript && (
            <div className="flex gap-2">
              <button onClick={copyToClipboard} className="px-3 py-1.5 text-sm border border-slate-200 rounded-lg hover:bg-slate-50 text-slate-600">
                Copy
              </button>
              <button onClick={downloadText} className="px-3 py-1.5 text-sm border border-slate-200 rounded-lg hover:bg-slate-50 text-slate-600">
                TXT
              </button>
              <button onClick={downloadPDF} className="px-3 py-1.5 text-sm bg-primary text-white rounded-lg hover:bg-primary-dark">
                PDF
              </button>
            </div>
          )}
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8">
        {!lifeScript ? (
          <div className="bg-white rounded-xl border border-slate-200 p-8">
            <div className="text-center mb-8">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-slate-900 mb-2">Generate Your Life Script</h2>
              <p className="text-slate-500">Transform your memories into a written biography</p>
            </div>

            {stats && (
              <div className="bg-slate-50 rounded-lg p-4 mb-6 flex items-center justify-between">
                <div>
                  <span className="text-2xl font-bold text-slate-900">{stats.totalEvents}</span>
                  <span className="text-slate-500 ml-2">life events</span>
                </div>
                <span className={`px-3 py-1 rounded-full text-sm font-medium ${stats.canGenerate ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>
                  {stats.canGenerate ? 'Ready to generate' : 'Need 3+ events'}
                </span>
              </div>
            )}

            <div className="mb-6">
              <label className="block text-sm font-medium text-slate-700 mb-3">Writing Style</label>
              <div className="grid gap-2">
                {STYLES.map(s => (
                  <label key={s.id} className={`flex items-center gap-3 p-4 rounded-lg border cursor-pointer transition ${selectedStyle === s.id ? 'border-primary bg-primary/5' : 'border-slate-200 hover:border-slate-300'}`}>
                    <input type="radio" name="style" value={s.id} checked={selectedStyle === s.id} onChange={e => setSelectedStyle(e.target.value)} className="text-primary" />
                    <div>
                      <div className="font-medium text-slate-900">{s.label}</div>
                      <div className="text-sm text-slate-500">{s.desc}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {error && <div className="mb-6 p-4 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">{error}</div>}

            <button
              onClick={generateLifeScript}
              disabled={generating || !stats?.canGenerate}
              className="w-full py-3 bg-primary hover:bg-primary-dark text-white font-medium rounded-lg transition disabled:opacity-50"
            >
              {generating ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Generating...
                </span>
              ) : 'Generate Life Script'}
            </button>

            {!stats?.canGenerate && (
              <p className="text-center text-sm text-slate-500 mt-4">
                <Link href="/interview" className="text-primary hover:underline">Start a conversation</Link> to add more events
              </p>
            )}
          </div>
        ) : (
          <div>
            {metadata && (
              <div className="bg-primary/5 border border-primary/20 rounded-lg p-4 mb-6">
                <div className="flex flex-wrap gap-4 text-sm text-primary">
                  <span><strong>Author:</strong> {metadata.userName}</span>
                  <span><strong>Events:</strong> {metadata.totalEvents}</span>
                  <span><strong>Style:</strong> {metadata.style}</span>
                  <span><strong>Generated:</strong> {new Date(metadata.generatedAt).toLocaleDateString()}</span>
                </div>
              </div>
            )}

            <div className="bg-white rounded-xl border border-slate-200 p-8">
              <div className="prose prose-slate max-w-none">
                {lifeScript.split('\n').map((p, i) => {
                  if (p.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold text-slate-900 mt-6 mb-4 first:mt-0">{p.replace('# ', '')}</h1>;
                  if (p.startsWith('## ')) return <h2 key={i} className="text-xl font-semibold text-slate-800 mt-5 mb-3">{p.replace('## ', '')}</h2>;
                  if (p.trim() === '') return <br key={i} />;
                  return <p key={i} className="text-slate-600 leading-relaxed mb-4">{p}</p>;
                })}
              </div>
            </div>

            <div className="text-center mt-6">
              <button onClick={() => { setLifeScript(null); setMetadata(null); }} className="text-primary hover:underline text-sm">
                Generate a new version
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
