'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

interface Stats {
  totalEvents: number;
  periodCounts: Record<string, number>;
  canGenerate: boolean;
}

interface Metadata {
  userName: string;
  totalEvents: number;
  periodsIncluded: string[];
  generatedAt: string;
  style: string;
}

const STYLE_OPTIONS = [
  { id: 'narrative', label: 'Narrative', description: 'Warm, engaging memoir-style prose' },
  { id: 'poetic', label: 'Poetic', description: 'Lyrical language with metaphors and imagery' },
  { id: 'journalistic', label: 'Journalistic', description: 'Clear, factual documentary style' },
];

export default function LifeScriptPage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  const [stats, setStats] = useState<Stats | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [lifeScript, setLifeScript] = useState<string | null>(null);
  const [metadata, setMetadata] = useState<Metadata | null>(null);
  const [selectedStyle, setSelectedStyle] = useState('narrative');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (status === 'loading') return;
    if (!session) {
      router.push('/login');
      return;
    }

    fetchStats();
  }, [session, status, router]);

  async function fetchStats() {
    try {
      const response = await fetch('/api/life-script');
      const data = await response.json();
      setStats(data);
    } catch (err) {
      console.error('Failed to fetch stats:', err);
    } finally {
      setLoading(false);
    }
  }

  async function generateLifeScript() {
    setGenerating(true);
    setError(null);

    try {
      const response = await fetch('/api/life-script', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ style: selectedStyle }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || 'Failed to generate');
        return;
      }

      setLifeScript(data.lifeScript);
      setMetadata(data.metadata);
    } catch (err) {
      console.error('Generation error:', err);
      setError('Failed to generate life script. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  function downloadAsText() {
    if (!lifeScript || !metadata) return;

    const content = `THE LIFE STORY OF ${metadata.userName.toUpperCase()}
Generated on ${new Date(metadata.generatedAt).toLocaleDateString()}
Style: ${metadata.style}
Based on ${metadata.totalEvents} documented life events

${'='.repeat(50)}

${lifeScript}

${'='.repeat(50)}
Generated by LifeStory Agent
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${metadata.userName.replace(/\s+/g, '_')}_Life_Story.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function copyToClipboard() {
    if (lifeScript) {
      navigator.clipboard.writeText(lifeScript);
      alert('Copied to clipboard!');
    }
  }

  if (status === 'loading' || loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-slate-600">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link href="/dashboard" className="text-slate-600 hover:text-slate-900">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
            </Link>
            <h1 className="text-xl font-bold text-slate-900">Life Script Generator</h1>
          </div>
          {lifeScript && (
            <div className="flex gap-2">
              <button
                onClick={copyToClipboard}
                className="px-3 py-1.5 text-sm border border-slate-300 rounded-lg hover:bg-slate-50 text-slate-700"
              >
                Copy
              </button>
              <button
                onClick={downloadAsText}
                className="px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Download
              </button>
            </div>
          )}
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8">
        {!lifeScript ? (
          /* Generation Form */
          <div className="bg-white rounded-xl border border-slate-200 p-8">
            <div className="text-center mb-8">
              <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-slate-900 mb-2">Generate Your Life Script</h2>
              <p className="text-slate-600">
                Transform your documented memories into a beautifully written biography.
              </p>
            </div>

            {/* Stats */}
            {stats && (
              <div className="bg-slate-50 rounded-lg p-4 mb-6">
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-2xl font-bold text-slate-900">{stats.totalEvents}</span>
                    <span className="text-slate-600 ml-2">life events documented</span>
                  </div>
                  {stats.canGenerate ? (
                    <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm">
                      Ready to generate
                    </span>
                  ) : (
                    <span className="px-3 py-1 bg-yellow-100 text-yellow-700 rounded-full text-sm">
                      Need at least 3 events
                    </span>
                  )}
                </div>
              </div>
            )}

            {/* Style Selection */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-slate-700 mb-3">
                Choose a writing style
              </label>
              <div className="grid gap-3">
                {STYLE_OPTIONS.map((style) => (
                  <label
                    key={style.id}
                    className={`flex items-start gap-3 p-4 border rounded-lg cursor-pointer transition ${
                      selectedStyle === style.id
                        ? 'border-purple-500 bg-purple-50'
                        : 'border-slate-200 hover:border-slate-300'
                    }`}
                  >
                    <input
                      type="radio"
                      name="style"
                      value={style.id}
                      checked={selectedStyle === style.id}
                      onChange={(e) => setSelectedStyle(e.target.value)}
                      className="mt-1"
                    />
                    <div>
                      <div className="font-medium text-slate-900">{style.label}</div>
                      <div className="text-sm text-slate-600">{style.description}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {error && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 text-red-700 rounded-lg">
                {error}
              </div>
            )}

            {/* Generate Button */}
            <button
              onClick={generateLifeScript}
              disabled={generating || !stats?.canGenerate}
              className="w-full py-3 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {generating ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  Generating your life story...
                </span>
              ) : (
                'Generate Life Script'
              )}
            </button>

            {!stats?.canGenerate && (
              <p className="text-center text-sm text-slate-500 mt-4">
                <Link href="/interview" className="text-purple-600 hover:text-purple-700">
                  Start an interview
                </Link>{' '}
                to document more life events.
              </p>
            )}
          </div>
        ) : (
          /* Generated Life Script Display */
          <div>
            {/* Metadata Bar */}
            {metadata && (
              <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-6">
                <div className="flex flex-wrap gap-4 text-sm">
                  <span className="text-purple-700">
                    <strong>Subject:</strong> {metadata.userName}
                  </span>
                  <span className="text-purple-700">
                    <strong>Events:</strong> {metadata.totalEvents}
                  </span>
                  <span className="text-purple-700">
                    <strong>Style:</strong> {metadata.style}
                  </span>
                  <span className="text-purple-700">
                    <strong>Generated:</strong>{' '}
                    {new Date(metadata.generatedAt).toLocaleDateString()}
                  </span>
                </div>
              </div>
            )}

            {/* Life Script Content */}
            <div className="bg-white rounded-xl border border-slate-200 p-8 shadow-sm">
              <div className="prose prose-slate max-w-none">
                {lifeScript.split('\n').map((paragraph, index) => {
                  if (paragraph.startsWith('# ')) {
                    return (
                      <h1 key={index} className="text-2xl font-bold text-slate-900 mt-8 mb-4 first:mt-0">
                        {paragraph.replace('# ', '')}
                      </h1>
                    );
                  }
                  if (paragraph.startsWith('## ')) {
                    return (
                      <h2 key={index} className="text-xl font-semibold text-slate-800 mt-6 mb-3">
                        {paragraph.replace('## ', '')}
                      </h2>
                    );
                  }
                  if (paragraph.trim() === '') {
                    return <br key={index} />;
                  }
                  return (
                    <p key={index} className="text-slate-700 leading-relaxed mb-4">
                      {paragraph}
                    </p>
                  );
                })}
              </div>
            </div>

            {/* Regenerate Option */}
            <div className="text-center mt-6">
              <button
                onClick={() => {
                  setLifeScript(null);
                  setMetadata(null);
                }}
                className="text-purple-600 hover:text-purple-700 text-sm"
              >
                Generate a new version
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
